development:
  # key and secret are displayed in skippr itself
  app_key: meineapp1
  app_secret: b6bf3849a8303058c058d301be415a86

  # the domain where the skippr installation is deployed that serves
  # the API you want to talk to
  domain: skippr.local
  port: 3030 

  # default: true - if the API is served via SSL
  secure: false

  # credentials in case API runs with http basic auth
  # user: myuser
  # password: mypassword

test:
  app_key: appkey_test
  app_secret: xxx
  domain: skippr.local
    
production:
  app_key: appkey_prod
  app_secret: xxx
  domain: skippr.local

