development:
  app_key: foobarbaz
  app_secret: 96d446d2cc305da05460ad41cdbd2e17
  domain: skippr.local
  port: 3000 
  secure: false

test:
  app_key: appkey_test
  app_secret: xxx
  domain: skippr.local
    
production:
  app_key: appkey_prod
  app_secret: xxx
  domain: skippr.local

